/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ojdbc.rmqhelper.ui;

import com.ojdbc.rmqhelper.rmq.Helper;
import com.ojdbc.rmqhelper.rmq.Sender;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.KeyStroke;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Arthur
 */
public class SendMsg extends javax.swing.JFrame {

    /**
     * Creates new form SendMsg
     */
    public SendMsg() {
        initComponents();
        setKeyMask(contentJTA);
        setKeyMask(sRoutingKeyJTF);
        setKeyMask(sExchangeNameJTF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TextJRB = new javax.swing.JRadioButton();
        bytesJRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentJTA = new javax.swing.JTextArea();
        sendBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sRoutingKeyJTF = new javax.swing.JTextField();
        sExchangeNameJTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sExchangeTypeItem = new javax.swing.JComboBox<>();

        setTitle("Send msg");

        buttonGroup1.add(TextJRB);
        TextJRB.setSelected(true);
        TextJRB.setText("文本");

        buttonGroup1.add(bytesJRB);
        bytesJRB.setText("byte[]");

        contentJTA.setColumns(20);
        contentJTA.setRows(5);
        jScrollPane1.setViewportView(contentJTA);

        sendBTN.setText("发送");
        sendBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendBTNMouseReleased(evt);
            }
        });

        jButton1.setText("关闭");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jLabel6.setText("RoutingKey");

        sRoutingKeyJTF.setText("test");

        sExchangeNameJTF.setText("test");
        sExchangeNameJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sExchangeNameJTFKeyPressed(evt);
            }
        });

        jLabel4.setText("ExchangeName");

        sExchangeTypeItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "direct", "topic", "fanout" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sExchangeNameJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(sRoutingKeyJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sExchangeTypeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextJRB)
                                .addGap(18, 18, 18)
                                .addComponent(bytesJRB))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sRoutingKeyJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sExchangeNameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sExchangeTypeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJRB)
                    .addComponent(bytesJRB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBTN)
                    .addComponent(jButton1))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBTNMouseReleased
        byte[] body = null;
        String sExchangeName = sExchangeNameJTF.getText();
        if (sExchangeName == null) {
            sExchangeName = "";
        }
        String sRoutingKey = sRoutingKeyJTF.getText();
        Helper.setsExchangeType(sExchangeTypeItem.getSelectedItem().toString());

        if (TextJRB.isSelected()) {
            try {
                body = contentJTA.getText().getBytes("UTF-8");

            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(SendMsg.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String[] text = contentJTA.getText().split(",");
            body = new byte[text.length];
            for (int i = 0; i < text.length; i++) {
                int a = Integer.parseInt(text[i]);
                body[i] = (byte) a;
            }
        }
        Helper.setsExchangeName(sExchangeName);
        Helper.setsRouterKey(sRoutingKey);
        Sender.sendMsg(body);
    }//GEN-LAST:event_sendBTNMouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseReleased

    private void sExchangeNameJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sExchangeNameJTFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sExchangeNameJTFKeyPressed

    private void setKeyMask(JTextComponent jtf) {
        int MASK = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
        jtf.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_A, MASK), "select-all");
        jtf.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_C, MASK), "copy");
        jtf.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_X, MASK), "cut");
        jtf.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_V, MASK), "paste");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton TextJRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton bytesJRB;
    private javax.swing.JTextArea contentJTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sExchangeNameJTF;
    private javax.swing.JComboBox<String> sExchangeTypeItem;
    private javax.swing.JTextField sRoutingKeyJTF;
    private javax.swing.JButton sendBTN;
    // End of variables declaration//GEN-END:variables
}
